from __future__ import annotations

from app.models import SectionDefinition


SERIAL_RX_SILENCE_TIMEOUT_OPTIONS = [
    {"value": str(seconds), "label": str(seconds)}
    for seconds in range(0, 601, 30)
]

ACTIVATION_SCHEDULE_FIELDS = [
    {
        "name": "activation_mode",
        "label": "Activation",
        "type": "select",
        "required": True,
        "default": "manual",
        "options": [
            {"value": "manual", "label": "Manual"},
            {"value": "scheduled", "label": "Scheduled"},
            {"value": "recurring", "label": "Recurring"},
        ],
    },
    {"name": "active_from_utc", "label": "Active from", "type": "date", "required": False},
    {"name": "active_until_utc", "label": "Active until", "type": "date", "required": False},
    {"name": "first_activation_utc", "label": "First activation (UTC)", "type": "date", "required": False, "form_visible": False},
    {"name": "recurrence_duration_minutes", "label": "Active for (hours)", "type": "number", "required": False},
    {"name": "recurrence_interval_value", "label": "Repeat every", "type": "number", "required": False},
    {
        "name": "recurrence_interval_unit",
        "label": "Repeat unit",
        "type": "select",
        "required": False,
        "options": [
            {"value": "", "label": "Select"},
            {"value": "day", "label": "Day(s)"},
            {"value": "week", "label": "Week(s)"},
            {"value": "month", "label": "Month(s)"},
            {"value": "year", "label": "Year(s)"},
        ],
    },
    {"name": "recurrence_until_utc", "label": "Repeat until (UTC)", "type": "date", "required": False, "form_visible": False},
]


SECTION_DEFINITIONS: dict[str, SectionDefinition] = {
    "modems": SectionDefinition(
        slug="modems",
        title="Interfaces",
        description="Manage APRSBox interfaces used for RF monitoring and TX, APRS-IS reception and transmission, and optional LAN port sharing.",
        table_name="modems",
        nav_key="modems",
        readonly_message="Interface settings are stored in SQLite and applied by APRSBox core.",
        list_title="Interface List",
        create_title="Add Interface",
        edit_title="Edit Interface",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {"name": "name", "label": "Name", "type": "text", "required": True},
            {
                "name": "band",
                "label": "Band condition assessment",
                "type": "select",
                "required": False,
                "default": "",
                "options": [
                    {"value": "", "label": "No band condition assessment"},
                    {"value": "2m", "label": "2m — assess propagation"},
                    {"value": "70cm", "label": "70cm — assess propagation"},
                ],
            },
            {
                "name": "modem_type",
                "label": "Type",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "SERIALL", "label": "SERIALL"},
                    {"value": "TCP", "label": "TCP"},
                    {"value": "OPENWEBRX_MQTT", "label": "OpenWebRX MQTT (RX only)"},
                    {"value": "APRSIS", "label": "APRS-IS (RX/TX)"},
                ],
            },
            {"name": "device_path", "label": "Path / Address / Filter", "type": "text", "required": False},
            {"name": "baud_rate", "label": "Baud Rate", "type": "number", "required": False},
            {
                "name": "serial_rx_silence_reconnect_seconds",
                "label": "RX Silence Reconnect Timeout (s)",
                "type": "select",
                "required": True,
                "default": "150",
                "options": SERIAL_RX_SILENCE_TIMEOUT_OPTIONS,
            },
            {"name": "enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "tx_blocked", "label": "Block TX on this interface", "type": "checkbox", "required": False},
            {"name": "tx_min_gap_seconds", "label": "TX Min Gap (s)", "type": "number", "required": True, "default": "0.35"},
            {"name": "station_id", "label": "Station", "type": "station_select", "required": False},
            {"name": "expose_port_enabled", "label": "Expose Port", "type": "checkbox", "required": False},
            {"name": "expose_allow_tx", "label": "Allow TX from remote clients", "type": "checkbox", "required": False},
            {"name": "expose_bind_address", "label": "Bind Address", "type": "text", "required": False, "default": "0.0.0.0"},
            {"name": "expose_port", "label": "Port", "type": "number", "required": False, "default": "8002"},
            {"name": "expose_whitelist", "label": "Whitelist", "type": "textarea", "required": False, "placeholder": "192.168.1.10\n192.168.1.0/24"},
        ],
    ),
    "servers": SectionDefinition(
        slug="servers",
        title="APRS-IS Servers",
        description="Store APRS-IS upstream definitions for later engine integration.",
        table_name="aprsis_servers",
        nav_key="servers",
        readonly_message="Server definitions can be entered now, but APRS-IS connectivity is not implemented yet.",
        fields=[
            {"name": "name", "label": "Name", "type": "text", "required": True},
            {"name": "host", "label": "Host", "type": "text", "required": True},
            {"name": "port", "label": "Port", "type": "number", "required": True},
            {"name": "use_tls", "label": "Use TLS", "type": "checkbox", "required": False},
            {"name": "enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "notes", "label": "Notes", "type": "textarea", "required": False},
        ],
    ),
    "igate": SectionDefinition(
        slug="igate",
        title="iGate Rules",
        description="Define future iGate policy entries. No packet transfer logic is implemented in this stage.",
        table_name="igate_rules",
        nav_key="igate",
        readonly_message="These records are placeholders for future iGate rule evaluation.",
        fields=[
            {"name": "name", "label": "Rule Name", "type": "text", "required": True},
            {"name": "direction", "label": "Direction", "type": "text", "required": True},
            {"name": "is_enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "policy_text", "label": "Policy Notes", "type": "textarea", "required": False},
        ],
    ),
    "digi": SectionDefinition(
        slug="digi",
        title="DIGI Rules",
        description="Prepare digipeating rule definitions without implementing digipeating itself.",
        table_name="digi_rules",
        nav_key="digi",
        readonly_message="DIGI policy storage exists; packet path handling will be added later.",
        fields=[
            {"name": "name", "label": "Rule Name", "type": "text", "required": True},
            {"name": "source_match", "label": "Source Match", "type": "text", "required": False},
            {"name": "destination_match", "label": "Destination Match", "type": "text", "required": False},
            {"name": "path_rewrite", "label": "Path Rewrite", "type": "text", "required": False},
            {"name": "is_enabled", "label": "Enabled", "type": "checkbox", "required": False},
        ],
    ),
    "objects": SectionDefinition(
        slug="objects",
        title="Objects",
        description="Prepare APRS object records with protocol-safe names, status, position, symbol and future RF path.",
        table_name="aprs_objects",
        nav_key="objects",
        readonly_message="Object transmission is not implemented yet. APRS object names are stored unpadded here, but will later be encoded into the fixed 9-character APRS object field with an automatic timestamp.",
        list_title="Object List",
        create_title="Add Object",
        edit_title="Edit Object",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {"name": "name", "label": "Object Name", "type": "text", "required": True, "maxlength": 9, "placeholder": "VOICE"},
            {
                "name": "lifetime",
                "label": "Object Lifetime",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "temporary", "label": "Temporary"},
                    {"value": "permanent", "label": "Permanent"},
                ],
            },
            {
                "name": "state",
                "label": "Object Activity",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "live", "label": "Live (*)"},
                    {"value": "killed", "label": "Killed (_)"},
                ],
            },
            {"name": "latitude", "label": "Latitude", "type": "text", "required": False},
            {"name": "longitude", "label": "Longitude", "type": "text", "required": False},
            {
                "name": "symbol_table",
                "label": "Symbol Table",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "/", "label": "Primary (/)"},
                    {"value": "\\", "label": "Alternate (\\)"},
                ],
            },
            {"name": "symbol_code", "label": "Symbol Code", "type": "text", "required": True, "maxlength": 1, "placeholder": "r"},
            {
                "name": "symbol_overlay",
                "label": "Overlay",
                "type": "select",
                "required": False,
                "options": [
                    {"value": "", "label": "None"},
                    *[{"value": str(value), "label": str(value)} for value in range(10)],
                    *[{"value": chr(code), "label": chr(code)} for code in range(ord("A"), ord("Z") + 1)],
                ],
                "default": "",
            },
            {
                "name": "interval_minutes",
                "label": "Send Interval",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "5", "label": "5m"},
                    {"value": "10", "label": "10m"},
                    {"value": "15", "label": "15m"},
                    {"value": "30", "label": "30m"},
                    {"value": "45", "label": "45m"},
                    {"value": "60", "label": "60m"},
                ],
                "default": "30",
            },
            {"name": "valid_until_utc", "label": "Valid until (UTC)", "type": "date", "required": False, "form_visible": False},
            *ACTIVATION_SCHEDULE_FIELDS,
            {"name": "path", "label": "Path", "type": "text", "required": False, "maxlength": 64},
            {"name": "station_id", "label": "Transmit via station", "type": "station_select", "required": False},
            {"name": "is_enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "comment", "label": "Comment", "type": "textarea", "required": True, "maxlength": 43, "placeholder": "Local voice repeater"},
        ],
    ),
    "items": SectionDefinition(
        slug="items",
        title="Items",
        description="Prepare APRS item records with protocol-safe names, status, position, symbol and future RF path.",
        table_name="aprs_items",
        nav_key="items",
        readonly_message="Item transmission is not implemented yet. APRS item names must be 3-9 printable ASCII characters and item format is historically less interoperable on RF than objects.",
        list_title="Item List",
        create_title="Add Item",
        edit_title="Edit Item",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {"name": "name", "label": "Item Name", "type": "text", "required": True, "maxlength": 9, "placeholder": "AID#2"},
            {
                "name": "state",
                "label": "Item State",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "live", "label": "Live (!)"},
                    {"value": "killed", "label": "Killed (_)"},
                ],
            },
            {"name": "latitude", "label": "Latitude", "type": "text", "required": False},
            {"name": "longitude", "label": "Longitude", "type": "text", "required": False},
            {
                "name": "symbol_table",
                "label": "Symbol Table",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "/", "label": "Primary (/)"},
                    {"value": "\\", "label": "Alternate (\\)"},
                ],
            },
            {"name": "symbol_code", "label": "Symbol Code", "type": "text", "required": True, "maxlength": 1, "placeholder": "A"},
            {
                "name": "symbol_overlay",
                "label": "Overlay",
                "type": "select",
                "required": False,
                "options": [
                    {"value": "", "label": "None"},
                    *[{"value": str(value), "label": str(value)} for value in range(10)],
                    *[{"value": chr(code), "label": chr(code)} for code in range(ord("A"), ord("Z") + 1)],
                ],
                "default": "",
            },
            {
                "name": "interval_minutes",
                "label": "Send Interval",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "5", "label": "5m"},
                    {"value": "10", "label": "10m"},
                    {"value": "15", "label": "15m"},
                    {"value": "30", "label": "30m"},
                    {"value": "45", "label": "45m"},
                    {"value": "60", "label": "60m"},
                ],
                "default": "30",
            },
            {"name": "valid_until_utc", "label": "Valid until (UTC)", "type": "date", "required": False, "form_visible": False},
            *ACTIVATION_SCHEDULE_FIELDS,
            {"name": "path", "label": "Path", "type": "text", "required": False, "maxlength": 64},
            {"name": "station_id", "label": "Transmit via station", "type": "station_select", "required": False},
            {"name": "is_enabled", "label": "Active", "type": "checkbox", "required": False},
            {"name": "comment", "label": "Comment", "type": "textarea", "required": False, "maxlength": 43, "placeholder": "First aid station"},
        ],
    ),
    "bulletins": SectionDefinition(
        slug="bulletins",
        title="Bulletins / Announcements",
        description="Prepare APRS message-format frames for bulletins and announcements.",
        table_name="bulletins",
        nav_key="bulletins",
        readonly_message="APRS bulletins and announcements use the message data type identifier (:). Text is limited to 67 characters and stored as strict ASCII only.",
        list_title="Bulletins / Announcements List",
        create_title="Add Bulletin / Announcement",
        edit_title="Edit Bulletin / Announcement",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {
                "name": "message_kind",
                "label": "Type",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "bulletin", "label": "General Bulletin"},
                    {"value": "announcement", "label": "Announcement"},
                    {"value": "group_bulletin", "label": "Group Bulletin"},
                ],
                "default": "bulletin",
            },
            {"name": "bulletin_code", "label": "Code", "type": "text", "required": False, "maxlength": 1, "placeholder": "0"},
            {"name": "group_name", "label": "Group", "type": "text", "required": False, "maxlength": 5, "placeholder": "WX"},
            {
                "name": "interval_minutes",
                "label": "Send Interval",
                "type": "select",
                "required": True,
                "options": [
                    {"value": "5", "label": "5m"},
                    {"value": "10", "label": "10m"},
                    {"value": "15", "label": "15m"},
                    {"value": "30", "label": "30m"},
                    {"value": "45", "label": "45m"},
                    {"value": "60", "label": "60m"},
                ],
                "default": "30",
            },
            {"name": "valid_until_utc", "label": "Valid until (UTC)", "type": "date", "required": False, "form_visible": False},
            *ACTIVATION_SCHEDULE_FIELDS,
            {"name": "path", "label": "Path", "type": "text", "required": False, "maxlength": 64},
            {"name": "station_id", "label": "Transmit via station", "type": "station_select", "required": False},
            {"name": "is_enabled", "label": "Enabled", "type": "checkbox", "required": False},
            {"name": "message_text", "label": "Message Text", "type": "textarea", "required": True, "maxlength": 67, "placeholder": "Net starts at 19:30 UTC"},
        ],
    ),
    "stations": SectionDefinition(
        slug="stations-config",
        title="My Stations",
        description="Create station identities. Each station gets its own entry in the sidebar for detailed configuration (beacon, status, position, symbol).",
        table_name="stations",
        nav_key="stations-config",
        readonly_message="",
        list_title="Stations",
        create_title="Add Station",
        edit_title="Edit Station",
        supports_editing=True,
        supports_delete=True,
        fields=[
            {"name": "name", "label": "Station Label", "type": "text", "required": True, "placeholder": "VHF"},
            {"name": "callsign", "label": "Callsign", "type": "text", "required": True, "placeholder": "N0CALL"},
            {"name": "ssid", "label": "SSID", "type": "text", "required": False, "placeholder": "1"},
            {"name": "enabled", "label": "Enabled", "type": "checkbox", "required": False},
        ],
    ),
}
